<?php
ini_set('memory_limit', '2048M');

include('../functions/phpfunctions.php');

//PHPExcel
require_once '../phpgeneration/PHPExcel.php';

//PHPExcel_IOFactory 
require_once '../phpgeneration/PHPExcel/IOFactory.php';

$flag = $_POST['flag'];
if($flag == '')
{
	$url = '../home/index.php?a_link=registrationdetails'; 
	header("location:".$url);
	exit;
}
elseif($flag == 'true')
{
	$id = $_GET['id'];
	$fromdate = $_POST['fromdate'];
	$todate = $_POST['todate'];
	$branch = $_POST['branch'];

	if($fromdate <> '' && $todate <> '')
	{
		
		$branchpiece = ($branch == "")?(""):(" AND inv_customerproduct.generatedby = '".$branch."' ");
		
		$query = "select ssm_products.productname,
count(*),
count(inv_mas_branch.branchname = 'BKG-Bangalore' OR NOT NULL) as 'BKG-Bangalore',
count(inv_mas_branch.branchname = 'BKG-Karnataka' OR NOT NULL) as 'BKG-Karnataka',
count(inv_mas_branch.branchname = 'CSD-Ahmedabad' OR NOT NULL) as 'CSD-Ahmedabad',
count(inv_mas_branch.branchname = 'CSD-Bangalore' OR NOT NULL) as 'CSD-Bangalore',
count(inv_mas_branch.branchname = 'CSD-Delhi' OR NOT NULL) as 'CSD-Delhi',
count(inv_mas_branch.branchname = 'CSD-Hyderabad' OR NOT NULL) as 'CSD-Hyderabad',
count(inv_mas_branch.branchname = 'CSD-Jaipur' OR NOT NULL) as 'CSD-Jaipur',
count(inv_mas_branch.branchname = 'CSD-Kolkata' OR NOT NULL) as 'CSD-Kolkata',
count(inv_mas_branch.branchname = 'CSD-Mumbai' OR NOT NULL) as 'CSD-Mumbai',
count(inv_mas_branch.branchname = 'CSD-Pune' OR NOT NULL) as 'CSD-Pune',
count(inv_mas_branch.branchname = 'BKG-Goa' OR NOT NULL) as 'BKG-Goa',
count(inv_mas_branch.branchname = 'CSD-Chennai' OR NOT NULL) as 'CSD-Chennai',
count(inv_mas_branch.branchname = 'BKM-Bangalore' OR NOT NULL) as 'BKM-Bangalore'
from ssm_callregister 
left join inv_mas_customer on inv_mas_customer.slno = ssm_callregister.customerid
left join ssm_products on ssm_products.slno = ssm_callregister.productname
left join inv_mas_branch on inv_mas_branch.slno = inv_mas_customer.branch
where ssm_callregister.date BETWEEN '2011-03-01' and '2011-03-31' group by ssm_products.productname;";
	
	}
	$result = runmysqlquery($query);
	
	// Create new Spreadsheet object
	$objPHPExcel= new Spreadsheet();
	
	//Set Active Sheet	
	$mySheet = $objPHPExcel->getActiveSheet();
		
	//Define Style for header row
	$styleArray = array(
						'font' => array('bold' => true,),
						'fill'=> array('fillType'=>\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID,'startColor'=> array('argb' => 'FFCCFFCC')),
						'borders' => array('allBorders'=> array('borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_MEDIUM))
					);
	//Apply style for header Row
	$mySheet->getStyle('A3:Q3')->applyFromArray($styleArray);
	
	//Merge the cell
	$mySheet->mergeCells('A1:Q1');
	$mySheet->mergeCells('A2:Q2');
	$objPHPExcel->setActiveSheetIndex(0)
				->setCellValue('A1', 'Relyon Softech Limited, Bangalore')
				->setCellValue('A2', 'Product Registration Details');
	$mySheet->getStyle('A1:A2')->getFont()->setSize(12); 	
	$mySheet->getStyle('A1:A2')->getFont()->setBold(true); 
	$mySheet->getStyle('A1:A2')->getAlignment()->setWrapText(true);
	
	
	//Fille contents for Header Row
	$objPHPExcel->setActiveSheetIndex(0)
			->setCellValue('A3', 'Sl No')
			->setCellValue('B3', 'Product')
			->setCellValue('C3', 'Customer')
			->setCellValue('D3', 'Pin Serial Number')
			->setCellValue('E3', 'Date')
			->setCellValue('F3', 'Computer ID')
			->setCellValue('G3', 'Soft Key')
			->setCellValue('H3', 'Generated By')
			->setCellValue('I3', 'Dealer')
			->setCellValue('J3', 'Bill Number')
			->setCellValue('K3', 'Billed Amount')
			->setCellValue('L3', 'Remarks')
			->setCellValue('M3', 'Scheme')
			->setCellValue('N3', 'Branch')
			->setCellValue('O3', 'Region')
			->setCellValue('P3', 'Usage Type')
			->setCellValue('Q3', 'Purchase Type');
				
	
	$j = 4;
	$slno = 0;
	while($fetch = mysqli_fetch_array($result))
	{
		$slno++;
		$mySheet->setCellValue('A' . $j,$slno)
				->setCellValue('B' . $j,$fetch['productname'])
				->setCellValue('C' . $j,$fetch['customername'])
				->setCellValue('D' . $j,$fetch['cardid'])
				->setCellValue('E' . $j,changedateformat($fetch['date']))
				->setCellValue('F' . $j,$fetch['computerid'])
				->setCellValue('G' . $j,$fetch['softkey'])
				->setCellValue('H' . $j,$fetch['userid'])
				->setCellValue('I' . $j,$fetch['dealername'])
				->setCellValue('J' . $j,$fetch['cusbillnumber'])
				->setCellValue('K' . $j,$fetch['billamount'])
				->setCellValue('L' . $j,$fetch['remarks'])
				->setCellValue('M' . $j,$fetch['schemename'])
				->setCellValue('N' . $j,$fetch['branchname'])
				->setCellValue('O' . $j,$fetch['region'])
				->setCellValue('P' . $j,$fetch['usagetype'])
				->setCellValue('Q' . $j,$fetch['purchasetype']);
				$j++;
	}
	
		//Define Style for content area
		$styleArrayContent = array(
							'borders' => array('allBorders'=> array('borderStyle' => \PhpOffice\PhpSpreadsheet\Style\Border::BORDER_THIN))
						);
		//Get the last cell reference
		$highestRow = $mySheet->getHighestRow(); 
		$highestColumn = $mySheet->getHighestColumn(); 
		$myLastCell = $highestColumn.$highestRow;
		
		//Deine the content range
		$myDataRange = 'A4:'.$myLastCell;
		if(mysqli_num_rows($result) <> 0)
		{
		//Apply style to content area range
			$mySheet->getStyle($myDataRange)->applyFromArray($styleArrayContent);
		}
		
		//set the default width for column
		$mySheet->getColumnDimension('A')->setWidth(6);
		$mySheet->getColumnDimension('B')->setWidth(30);
		$mySheet->getColumnDimension('C')->setWidth(35);
		$mySheet->getColumnDimension('D')->setWidth(17);
		$mySheet->getColumnDimension('E')->setWidth(13);
		$mySheet->getColumnDimension('F')->setWidth(16);
		$mySheet->getColumnDimension('G')->setWidth(15);
		$mySheet->getColumnDimension('H')->setWidth(18);
		$mySheet->getColumnDimension('I')->setWidth(43);
		$mySheet->getColumnDimension('J')->setWidth(12);
		$mySheet->getColumnDimension('K')->setWidth(15);
		$mySheet->getColumnDimension('L')->setWidth(39);
		$mySheet->getColumnDimension('M')->setWidth(26);
		$mySheet->getColumnDimension('N')->setWidth(15);
		$mySheet->getColumnDimension('O')->setWidth(10);
		$mySheet->getColumnDimension('P')->setWidth(12);
		$mySheet->getColumnDimension('Q')->setWidth(14);
		
		$addstring = "/user";
		if($_SERVER['HTTP_HOST'] == "meghanab" || $_SERVER['HTTP_HOST'] == "archanaab")
			$addstring = "/saralimax-user";
		if($id == 'toexcel')
		{
			$query = 'select slno,username from inv_mas_users where slno = '.$userid.'';
			$fetchres = runmysqlqueryfetch($query);
			$localdate = datetimelocal('Ymd');
			$localtime = datetimelocal('His');
			$filebasename = "RegistrationReport".$localdate."-".$localtime."-".strtolower($fetchres['username']).".xls";
			$query1 ="INSERT INTO inv_logs_reports(userid,`date`,`time`,`type`,`data`,system) VALUES('".$userid."','".datetimelocal('Y-m-d')."','".datetimelocal('H-i')."','excel_registration_report',\"".$query."\",'".$_SERVER['REMOTE_ADDR']."')";
			$result = runmysqlquery($query1);	
	
			$filepath = $_SERVER['DOCUMENT_ROOT'].$addstring.'/filecreated/'.$filebasename;
			$downloadlink = 'http://'.$_SERVER['HTTP_HOST'].$addstring.'/filecreated/'.$filebasename;
			
			$objWriter = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($objPHPExcel, 'Xls');
			$objWriter->save($filepath);
			
			$fp = fopen($filebasename,"wa+");
			if($fp)
			{
				downloadfile($filepath);
				fclose($fp);
			} 
			//unlink($filepath);
			unlink($filebasename);
			exit; 
		}
		elseif($id == 'view')
		{
			$query1 ="INSERT INTO inv_logs_reports(userid,`date`,`time`,`type`,`data`,system) VALUES('".$userid."','".datetimelocal('Y-m-d')."','".datetimelocal('H-i')."','view_registration_report',\"".$query."\",'".$_SERVER['REMOTE_ADDR']."')";
			$result = runmysqlquery($query1);
	
			$localdate = datetimelocal('Ymd');
			$localtime = datetimelocal('His');
			$filename = "viewregistrationreport".$localdate."-".$localtime.".htm";
			$filepath = $_SERVER['DOCUMENT_ROOT'].$addstring.'/filecreated/'.$filename;
	
			$objWriter = \PhpOffice\PhpSpreadsheet\IOFactory::createWriter($objPHPExcel, 'Html');
			$objWriter->save($filepath);
			
			// get contents of a file into a string
			$handle = fopen($filepath, "r");
			$contents = fread($handle, filesize($filepath));
			fclose($handle);
			
			echo($contents);
			unlink($filepath);
			exit;
		}
	}
	

?>
